### ISSUE TITLE
heroku logs giving rejection error

### ISSUE THREAD

**Issue by abdulhannanali** [abdulhannanali/loklak-telegram-chat-bot#11]
I am receiving this rejection error when entering /search [query].

```
2015-12-23T18:34:50.039624+00:00 app[web.1]: Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"[Error]: Bad Request: text is empty"}
2015-12-23T18:34:50.039629+00:00 app[web.1]:     at /app/node_modules/node-telegram-bot-api/src/telegram.js:111:15
2015-12-23T18:34:50.039630+00:00 app[web.1]:     at tryCatcher (/app/node_modules/bluebird/js/main/util.js:26:23)
2015-12-23T18:34:50.039632+00:00 app[web.1]:     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/main/promise.js:507:31)
2015-12-23T18:34:50.039632+00:00 app[web.1]:     at Promise._settlePromiseAt (/app/node_modules/bluebird/js/main/promise.js:581:18)
2015-12-23T18:34:50.039633+00:00 app[web.1]:     at Promise._settlePromises (/app/node_modules/bluebird/js/main/promise.js:697:14)
2015-12-23T18:34:50.039634+00:00 app[web.1]:     at Async._drainQueue (/app/node_modules/bluebird/js/main/async.js:123:16)
2015-12-23T18:34:50.039635+00:00 app[web.1]:     at Async._drainQueues (/app/node_modules/bluebird/js/main/async.js:133:10)
2015-12-23T18:34:50.039636+00:00 app[web.1]:     at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/main/async.js:15:14)
2015-12-23T18:34:50.039636+00:00 app[web.1]:     at processImmediate [as _immediateCallback] (timers.js:383:17)

```

**Comment by abdulhannanali** [comment]
it's probably being emitted in case when there is no tweet found for a search result. this needs to be solved in the next commit

**Comment by abdulhannanali** [comment]
assigning this to myself

**Comment by abdulhannanali** [comment]
The errorMessage took wrong arguments it took the error but it didn't have the message as argument to which the chat is sent. That's why it was giving an error.
Now it's corrected though...
